---
title: "Question 2"
author: "Jonathan Kerr"
date: "18/02/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)
kaggle_data_cleaned <- readRDS("kaggle_data_cleaned.rds")
```

### Check if data appears linear for total amount of money raised (Question 2)

```{r}
# EDA
eda <- kaggle_data_cleaned %>% 
  select(first_funding_at) %>% 
  arrange(first_funding_at)
head(eda)

# bucket first_funding_at by year and filter bad data (funding 0011)
first_year <- 1980
first_funding_date <- kaggle_data_cleaned %>% 
  mutate(first_funding_at = as.numeric(substring(first_funding_at, 1,4)) ) %>% 
  filter(first_funding_at >= first_year) %>% 
  filter(first_funding_at <= 2014)# %>%

model <- lm(formula = seed ~ first_funding_at, data = first_funding_date)
plot(seed ~ first_funding_at, data=first_funding_date); abline(model) 
summary(model) 

# The outliers seem to be throwing things off.  Filter out anything greater than 5 SDs from mean
outlier_metric <-  mean(first_funding_date$seed) + (5 * sd(first_funding_date$seed)) # six 9's of precision
first_funding_date_out <- first_funding_date %>% 
  filter(seed < outlier_metric)

model <- lm(formula = seed ~ first_funding_at, data = first_funding_date_out)
plot(seed ~ first_funding_at, data=first_funding_date_out); abline(model) 
summary(model) 

# This looks like it could be skewed up by the larger number of rounds in later years.  Try comparing means instead
mean_compare <- first_funding_date_out %>% 
    group_by(first_funding_at) %>%
    dplyr::summarize(seed_mean = mean(seed, na.rm=TRUE))

model <- lm(formula = seed_mean ~ first_funding_at, data = mean_compare)
plot(seed_mean ~ first_funding_at, data=mean_compare); abline(model) 
summary(model) 
```
### Can we seperate the chance of seed funding from the amount?

```{r}
# Add new columns
first_funding_date_out$got_seed <- first_funding_date_out$seed > 0
first_funding_date_out$log_seed <- log(first_funding_date_out$seed)
first_funding_date_out[is.infinite(first_funding_date_out$log_seed),]$log_seed <- -9999999999999
first_funding_date_with_seed <- first_funding_date_out[first_funding_date_out$got_seed == TRUE,]

# Model seed chance
annualData <- do.call(data.frame, aggregate(cbind(seed, got_seed, log_seed)  ~ first_funding_at, data=first_funding_date_out, FUN=mean))
model.seed_chance <- lm(formula = got_seed ~ first_funding_at, data = annualData[annualData$first_funding_at >= 1990,])
plot(got_seed ~ first_funding_at, data=annualData); abline(model.seed_chance) 
print(summary(model.seed_chance))

# Model seed amount
annualData.with_seed <- do.call(data.frame, aggregate(cbind(seed, got_seed, log_seed)  ~ first_funding_at, data=first_funding_date_with_seed, FUN=mean))
model.seed_amount <- lm(formula = seed ~ first_funding_at, data = annualData.with_seed)
plot(seed ~ first_funding_at, data=annualData.with_seed); abline(model.seed_amount) 
print(summary(model.seed_amount))

# Model log seed amount
model.seed_amount_log <- lm(formula = log_seed ~ first_funding_at, data = annualData.with_seed, na.action=na.omit)
plot(log_seed ~ first_funding_at, data=annualData.with_seed); abline(model.seed_amount_log) 
print(summary(model.seed_amount_log))
```
